# https://hexo.io/zh-cn/docs/github-pages.html
sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo
install:
  - npm install -g hexo
  - npm install
script:
  - mkdir themes/next
  # clone next theme
  - git clone --depth=1 https://github.com/theme-next/hexo-theme-next themes/next
  # copy the custom next theme config file
  - no | mv themes/next/* -i themes/hexo-theme-next/
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
    # all_branches: true # solve a permission problem
  target_branch: master
  local-dir: public
