# https://hexo.io/zh-cn/docs/github-pages.html
sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo
install:
  - npm install -g hexo
  - npm install
script:
  - mkdir themes/next
  - curl -s https://api.github.com/repos/iissnan/hexo-theme-next/releases/latest | grep tarball_url | cut -d '"' -f 4 | wget -i - -O- | tar -zx -C themes/next --strip-components=1
  - no | mv themes/next/* -i themes/hexo-theme-next/
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
